# general config
entity: 'advanced-topics-in-deep-learning'
seed: 42
gpus: 1
num_workers: 8

# backbone and dataset
repo_or_dir: pytorch/vision:v0.10.0          # facebookresearch/WSL-Images
model: resnet50 # wide_resnet50_2 #          # resnext101_32x8d_wsl
pretrained: True
dataset: ./datasets/imagenette2 #imagenette2-160
num_of_classes: 10

# Moco model
batch_size: 32
channels: 128
mlp_out_features: 128
max_steps: 100_000
queue_size: 16_000
temperature: 0.2
momentum: 0.999
moco_sgd_momentum: 0.9
do_all_dataset_in_memory: False #True
check_val_every_n_epoch: 1
model_lr: 0.01
moco_sgd_wegiht_decay: 0.0001

# linear model
linear_batch_size: 256
linear_max_epoch: 100
linear_lr: 30 #0.15
linear_sgd_momentum: 0.9
linear_sgd_weight_decay: 0

# augmentations
RandomSizedCrop: 224
ColorJitter_brightness: 0.4
ColorJitter_contrast: 0.4
ColorJitter_saturation: 0.4
ColorJitter_hue: 0.1 #0.4
GaussianBlur_min: 0.1
GaussianBlur_max: 2
RandomGrayscale: 0.2
