entity: 'advanced-topics-in-deep-learning'
seed: 42
repo_or_dir: pytorch/vision:v0.10.0          # facebookresearch/WSL-Images
model: resnet50 # wide_resnet50_2 #          # resnext101_32x8d_wsl
pretrained: True
channels: 128
max_steps: 100_000
gpus: 1
queue_size: 16_000
temperature: 0.2
momentum: 0.999
mlp_out_features: 128
num_of_classes: 10
batch_size: 32
dataset: ./datasets/imagenette2
do_all_dataset_in_memory: True
check_val_every_n_epoch: 1
num_workers: 8
model_lr: 0.01

# linear model
linear_batch_size: 256
linear_max_epoch: 100
linear_lr: 0.015

RandomSizedCrop: 224
ColorJitter_brightness: 0.4
ColorJitter_contrast: 0.4
ColorJitter_saturation: 0.4
ColorJitter_hue: 0.4
GaussianBlur_min: 0.1
GaussianBlur_max: 2
RandomGrayscale: 0.2
